baseURL: /
languageCode: en-us
title: Portworx Documentation
pygmentsUseClasses: true
pygmentsCodeFences: true
enableGitInfo: true
theme: pxdocs-tooling

params:
  narrowToolbarTitle: Portworx Documentation
  wideToolbarTitle: Documentation
  description: The documentation for Portworx
  githubRepo: https://github.com/portworx/pxdocs
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
  Redirects:
    baseName: redirects
    isPlainText: true
    mediaType: application/json
    notAlternative: true

outputs:
  home:
    - HTML
    - RSS
    - Algolia
    - Redirects